[[monitoring]]
= Monitoring
:_basedir: ../
:_imagesdir: images/


DataNucleus allows a user to enable various MBeans internally. These can then be used for monitoring the number of datastore calls etc.


== Via API

The simplest way to monitor DataNucleus is to use its API for monitoring. 
Internally there are several MBeans (as used by JMX) and you can navigate to these to get the required information. 
To enable this set the persistence property *datanucleus.enableStatistics* to _true_. 
There are then two sets of statistics; one for the EMF and one for each EM. You access these as follows

[source,java]
-----
JPAEntityManagerFactory dnEMF = (JPAEntityManagerFactory)emf;
FactoryStatistics stats = dnEMF.getNucleusContext().getStatistics();
... (access the statistics information)


JPAEntityManager dnEM = (JPAEntityManager)em;
ManagerStatistics stats = dnEM.getExecutionContext().getStatistics();
... (access the statistics information)
-----


== Using JMX
                
The MBeans used by DataNucleus can be accessed via JMX at runtime. More about JMX http://www.oracle.com/technetwork/java/javase/tech/javamanagement-140525.html[here].

An MBean server is bundled with Sun/Oracle JRE since Java5, and you can easily activate DataNucleus MBeans registration by creating your EMF 
with the persistence property *datanucleus.jmxType* as _platform_

Additionally, setting a few system properties are necessary for configuring the Sun JMX implementation. The minimum properties required are the following:

* com.sun.management.jmxremote
* com.sun.management.jmxremote.authenticate
* com.sun.management.jmxremote.ssl
* com.sun.management.jmxremote.port=<port number>

Usage example:

-----
java -cp TheClassPathInHere
     -Dcom.sun.management.jmxremote
     -Dcom.sun.management.jmxremote.authenticate=false
     -Dcom.sun.management.jmxremote.ssl=false
     -Dcom.sun.management.jmxremote.port=8001
     TheMainClassInHere
-----
                
Once you start your application and DataNucleus is initialized you can browse DataNucleus MBeans using a tool called jconsole (jconsole is distributed with the Sun JDK) via the URL:

-----
service:jmx:rmi:///jndi/rmi://hostName:portNum/jmxrmi
-----
                
Note that the mode of usage is presented in this document as matter of example, and by no means we recommend to disable authentication and secured communication channels. 
Further details on the Sun JMX implementation and how to configure it properly can be found http://java.sun.com/j2se/1.5.0/docs/guide/management/agent.html[here].

DataNucleus MBeans are registered in a MBean Server when DataNucleus is started up (e.g. upon JPA EMF instantiation). 
To see the full list of DataNucleus MBeans, refer to the http://www.datanucleus.org/javadocs/core/latest/org/datanucleus/management/runtime/package-summary.html[javadocs].
                
