[[jpa_getting_started]]
= JPA Getting Started Guide (v{version})
:_basedir: ../
:_imagesdir: images/
:jpa:
:notoc:


Developing applications is, in general, a complicated task, involving many components. Developing all of these components can be very time consuming.
The Java Persistence API (JPA) was designed to alleviate some of this time spent, providing an API to allow java developers to persist object-oriented 
data into relational databases (RDBMS). 

DataNucleus JPA provides an implementation of this JPA _standard_, allowing you, the user, to persist your
object-oriented data to not only the RDBMS datastores the standard was intended for, but also to a wide range of other datastores.
These include popular map stores such as Cassandra and HBase, the Neo4j graph store, spreadsheets in Excel or OpenDocument formats, 
JSON formatted Amazon and Google Storage options, the popular MongoDB JSON-like document store, as well as ubiquitous LDAP and more besides.
DataNucleus was the first JPA provider to support persistence to non-RDBMS datastores, and still has a wider range of supported stores than any other JPA provider.

DataNucleus doesn't purport to be the best solution to every problem. 
For example, where you want to bulk persist large amounts of data then other solutions that get closer to the datastore API would be more appropriate.
Where you want to tailor the precise query sent to the datastore to take advantage of some datastore-specific feature is another situation
in which you may find a hand-crafted solution more appropriate. 
That said, the range of capabilities of DataNucleus JPA cover a wide range of use-cases, the barrier to entry for use of DataNucleus is very low. 
You do not need to necessarily be an expert in all features of the chosen datastore to use it. It shields you from the majority of the
more routine handling, whilst still letting you have a high degree of control over its behaviour and we hope that you benefit from its features.


== Key Points

There are some key points to bear in mind when starting using JPA for java persistence.

* Your classes should be exactly that, _your_ classes. DataNucleus imposes little to nothing on you. Some JPA providers insist on a
_default constructor_, but DataNucleus provides its enhancer to add that automatically when not present.
* Your JPA entity classes need link:enhancer.html[bytecode enhancing] for use in the persistence process, but this can be an automatic post-compilation step.
* To persist objects of classes you firstly need to *define which classes are persistable, and how they are persisted*. 
Start under the link:mapping.html[JPA Mapping Guide]
* Use of JPA requires an link:persistence.html#emf[EntityManagerFactory] to access the datastore.
* The persistence itself is controlled by an link:persistence.html#em[EntityManager] and each object to be persisted will
have different link:persistence.html#lifecycle[lifecycle states] that you need to have an understanding of.
* You retrieve objects either by their link:persistence.html#_finding_an_object_by_its_identity[identity], or using a link:query.html[query]. 
With JPA you can use link:query.html#jpql[JPQL], link:query.html#native[Native (SQL)], or link:query.html#criteria[Criteria] query languages
* You will need `javax.persistence` as well as `datanucleus-api-jpa`, `datanucleus-core` and the `datanucleus-XXX` jar for whichever datastore you are using.



== Understanding the JARs

DataNucleus has a modular architecture and you will need to make use of multiple JARs in your application, as follows

* `javax.persistence.jar` : This is the JPA API. This is basically a collection of interfaces, annotations and helper classes.
* `datanucleus-api-jpa.jar` : This is DataNucleus' implementation of the JPA API. It implements the interfaces defined in _javax.persistence.jar_.
* `datanucleus-core.jar` : This provides the basic DataNucleus persistence mechanism, and is required by all DataNucleus plugins.
* `datanucleus-{datastore}.jar` ({datastore} is 'rdbms', 'mongodb', 'cassandra', etc) : This provides persistence to the specific type of datastore that the JAR is for.
* `datanucleus-jpa-query.jar` : This provides an _annotation processor_ and is used by the JPA Criteria mechanism to generate the JPA static metamodel classes used at runtime.

There are various additional JARs that can be used, providing support for additional (non-standard) types, or features (such as third-party caching products).

NOTE: DataNucleus jars make use of a plugin mechanism, whereby they have a file `plugin.xml` that defines capabilities of each jar. 
Attempting to "merge" the DataNucleus jars (without merging `plugin.xml` and  `MANIFEST.MF`) can result in problems and people are advised to not do this, 
or if they really want to then use something like http://one-jar.sourceforge.net/[one-jar].


include::tutorial.adoc[leveloffset=+1]
