[[metadata]]
= JPA Metadata Reference (v{version})
:_basedir: ../
:_imagesdir: images/
:jpa:

JPA requires the persistence of classes to be defined via _metadata_. JPA _metadata_ can be provided by way of Java annotations, and/or by XML metadata
in a file `orm.xml` (normally situated under `META-INF` at the root of the CLASSPATH).

You are free to use whichever you prefer.

TIP: We recommend keeping all schema information out of annotations, and put it in `orm.xml`. This then has the advantage that you have
database independence, and can simply swap in a different `orm.xml` when dealing with a different schema.

If you define both java annotations and `orm.xml` then the XML will override anything in the annotations.

TIP: By default any XML Metadata will be validated for accuracy when loading it. Obviously XML is defined by a DTD or XSD schema and so should follow that.
You can turn off such validations by setting the persistence property *datanucleus.metadata.xml.validate* to false when creating your EntityManagerFactory.
Note that this only turns off the XML strictness validation, and _not_ the checks on inconsistency of specification of relations etc.


include::annotations.adoc[leveloffset=+1]
include::metadata_xml.adoc[leveloffset=+1]

