[[jdo_getting_started]]
= JDO Getting Started Guide (v{version})
:_basedir: ../
:_imagesdir: images/
:jdo:


Developing applications is, in general, a complicated task, involving many components. Developing all of these components can be very time consuming.
The Java Data Objects API (JDO) was designed to alleviate some of this time spent, providing an API to allow java developers to persist object-oriented 
data into any database, and providing a query language using the same Java syntax as the developer is already familiar with. 

DataNucleus JDO provides an implementation of this JDO _standard_, allowing you, the user, to persist your
object-oriented data to not only the RDBMS datastores the standard was intended for, but also to a wide range of other datastores.
These include popular map stores such as Cassandra and HBase, the Neo4j graph store, spreadsheets in Excel or OpenDocument formats, 
JSON formatted Amazon and Google Storage options, the popular MongoDB JSON-like document store, as well as ubiquitous LDAP and more besides.

DataNucleus doesn't purport to be the best solution to every problem. 
For example, where you want to bulk persist large amounts of data then other solutions that get closer to the datastore API would be more appropriate.
Where you want to tailor the precise query sent to the datastore to take advantage of some datastore-specific feature is another situation
in which you may find a hand-crafted solution more appropriate. 
That said, the range of capabilities of DataNucleus JDO cover a wide range of use-cases, the barrier to entry for use of DataNucleus us very low. 
You do not need to necessarily be an expert in all features of the chosen datastore to use it. It shields you from the majority of the
more routine handling, whilst still letting you have a high degree of control over its behaviour and we hope that you benefit from its features.


== Key Points

There are some key points to bear in mind when starting using JDO for java persistence.

* Your classes should be exactly that, _your_ classes. DataNucleus imposes little to nothing on you. 
The DataNucleus enhancer provides for adding on a _default constructor_ if you haven't provided one.
* Your JDO persistent classes need link:enhancer.html[bytecode enhancing] for use in the persistence process, but this can be an automatic post-compilation step.
* To persist objects of classes you firstly need to *define which classes are persistable, and how they are persisted*. 
Start under the link:mapping.html[JDO Mapping Guide]
* Use of JDO requires a link:persistence.html#pmf[PersistenceManagerFactory] to access the datastore.
* The persistence itself is controlled by a link:persistence.html#pm[PersistenceManager] and each object to be persisted will
have different link:persistence.html#lifecycle[lifecycle states] that you need to have an understanding of.
* You retrieve objects either by their identity, or using a link:query.html[query]. With JDO you can use JDOQL or SQL query languages
* You will need `javax.jdo` as well as `datanucleus-api-jdo`, `datanucleus-core` and the `datanucleus-XXX` jar for whichever datastore you are using.


== Understanding the JARs

DataNucleus has a modular architecture and you will need to make use of multiple JARs in your application, as follows

* *javax.jdo.jar* : This is the JDO API. This is basically a collection of interfaces, annotations and helper classes.
* *datanucleus-api-jdo.jar* : This is DataNucleus' implementation of the JDO API. It implements the interfaces defined in _javax.jdo.jar_.
* *datanucleus-core.jar* : This provides the basic DataNucleus persistence mechanism, and is required by all DataNucleus plugins.
* *datanucleus-XXX.jar* (XXX is 'rdbms', 'mongodb', 'cassandra', etc) : This provides persistence to the specific type of datastore that the JAR is for.
* *datanucleus-jdo-query.jar* : This provides an _annotation processor_ and is used by the JDO Typed Query mechanism to generate the Q classes used at runtime.

There are various additional JARs that can be used, providing support for additional (non-standard) types, or features (such as third-party caching products).


include::tutorial.adoc[leveloffset=+1]
