[[query]]
= JDO Query Guide
:_basedir: ../
:_imagesdir: images/


Once you have persisted objects you need to query them. 
For example if you have a web application representing an online store, the user asks to see all products of a particular type, ordered by the price. 
This requires you to query the datastore for these products. JDO specifies support for 

* link:#jdoql[JDOQL] : a string-based query language using Java syntax.
* link:#typed[Typed] : following JDOQL syntax but providing an API supporting refactoring of classes and the queries they are used in.
* link:#sql[SQL] typically only for RDBMS
* link:#jpql[JPQL] : not explicitly part of the JDO spec, but provided by DataNucleus JDO.

Which query language is used is down to the developer. 
The data-tier of an application could be written by a primarily Java developer, who would typically think in an object-oriented way and so would likely prefer *JDOQL*. 
On the other hand the data-tier could be written by a datastore developer who is more familiar with SQL concepts and so could easily make more use of *SQL*.
This is the power of an implementation like DataNucleus in that it provides the flexibility for different people to develop the data-tier utilising their own skills 
to the full without having to learn totally new concepts.

There are 2 categories of queries with JDO :-

* *Programmatic Query* where the query is defined using the JDO Query API.
* *Named Query* where the query is defined in MetaData and referred to by its name at runtime(for link:#jdoql_named[JDOQL], link:#sql_named[SQL].


// include::_query_api.adoc[leveloffset=+1]

// include::_query_jdoql.adoc[leveloffset=+1]
// include::_query_typed.adoc[leveloffset=+1]
// include::_query_sql.adoc[leveloffset=+1]
// include::_query_jpql.adoc[leveloffset=+1]
// include::_query_stored_procedures.adoc[leveloffset=+1]

// include::_query_cache.adoc[leveloffset=+1]


