[[extensions]]
= DataNucleus ExtensionPoints Guide
:_basedir: ../
:_imagesdir: images/
:numbered:

== Plugin Mechanism
DataNucleus products are built using a plugin mechanism, allowing plugins to operate together.
This plugin mechanism involves the use of a file `plugin.xml` situated at the root of the CLASSPATH, containing a definition of the
ExtensionPoints and Extensions that the plugin utilises/provides. 
The plugin mechanism originated in the Eclipse IDE, but has no dependencies on Eclipse.
This plugin mechanism is useful also from a user viewpoint in that you, the user, could provide plugins that use these ExtensionPoints and extend the capabilities of DataNucleus.
Plugins are loaded by a plugin manager when DataNucleus is initialised at runtime, and this plugin manager uses a registry mechanism, inspecting jars in the CLASSPATH.

A plugin loadable by DataNucleus requires 2 components.

[[plugin_xml]]
=== plugin.xml
A file `plugin.xml` should be placed at the root of the plugin, and should be something like this (refer to the specific ExtensionPoint(s) being provided for precise content).

[source,xml]
------------
<?xml version="1.0"?>
<plugin id="mydomain" name="DataNucleus plug-ins" provider-name="My Company">
    <extension point="org.datanucleus.type_converter">
    <type-converter name="dn.uri-string" member-type="java.net.URI" datastore-type="java.lang.String" converter-class="mydomain.converters.URIStringConverter"/>
    </extension>
</plugin>
------------

[[MANIFEST]]
=== MANIFEST.MF
A minimum `META-INF/MANIFEST.MF` for a plugin jar should look like this
---------------------------
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: myplugin
Bundle-SymbolicName: mydomain.myplugin
Bundle-Version: 1.0.0
Bundle-Vendor: My Company
---------------------------

This provides basic information for DataNucleus, but also for the OSGi environment, should it ever be required.

Each DataNucleus bundle uses a version schema that has the following versioning scheme (OSGi 3.0 §3.2.4): _major.minor.revision.qualifier_
major, minor and revision are numeric values, and qualifier is an alphanumeric.

Each bundle has the version value set in the `/META-INF/MANIFEST.MF` file, Bundle-Version entry.
-----
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: DataNucleus Enhancer
Bundle-SymbolicName: org.datanucleus.enhancer;singleton:=true
Bundle-Vendor: DataNucleus
Bundle-Version: 1.2.0.b2
-----

The most common version compatibility policies are (OSGI 3.0 §3.6.2):

* major - An incompatible update
* minor - A backward compatible update
* revision - A change that does not affect the interface: for example, a bug fix


When your bundle depends on another bundle, you must declare it in the MANIFEST file, via the Require-Bundle entry.

For example, the RDBMS plugin (org.datanucleus.store.rdbms) plug-in depends on the core (org.datanucleus) plug-in.
-----
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: DataNucleus RDBMS
Bundle-SymbolicName: org.datanucleus.store.rdbms;singleton:=true
Bundle-Vendor: DataNucleus
Bundle-Version: 1.2.0.b2
Bundle-Localization: plugin
Require-Bundle: org.datanucleus
-----
See more on the OSGi 3.0 specification §3.13.1.

If a bundle depends on a specific version of a bundle, you must declare it in the _Require-Bundle_ entry, bundle-version parameter. For example
-----
Require-Bundle: org.datanucleus;bundle-version=(1.2.0.b2, 2.0)
-----
See more on the OSGi 3.0 specification §3.2.5 and §3.13.1 chapters.

All DataNucleus plugins use the Maven _bundle_ plugin to auto-generate the `MANIFEST.MF` file. This means that the version in the `pom.xml` is taken for the
bundle version, and the dependencies are auto-generated from imports etc. We recommend that you use this same method for your own plugins.



### Plugins in a Non-managed environment

A non-managed environment is a runtime environment where DataNucleus runs and plug-ins are not managed by a container. 
In this environment the plug-in discovery and lifecycle is managed by DataNucleus.
JavaSE and JavaEE runtimes are considered _non-managed_ environments.
In non managed environments there is no lifecycle itself for plug-ins. 

There is a 1 to N instance relationship from DataNucleus to a plug-in per PMF/EMF. 
More exactly, if only one PMF/EMF exists, there is only one Plug-in instance for a Connection Pool Plug-in, and if "N" PMF/EMF exist, there are "N" Plug-in instances for a ConnectionPool Plug-in.
Extensions implemented by plugins are instantiated on demand and terminated on PMF/EMF closing, PM/EM closing or in another form depending on what the extension is used for.


### Plugins in a Managed environment

Managed environment is a runtime environment where DataNucleus plug-ins are managed by a container. 
The discovery, registry and lifecycle of plug-ins are controlled by the container. 
There is no plug-in instance relationship from DataNucleus to a plug-in regarding PMF/EMF instances. 
In managed environments, there is only one plug-in instance for one or "N" PMF/EMFs. Again, this is managed by the container.

DataNucleus supports OSGi containers as managed environment. In OSGi managed environments plug-in lifecycle is determined by the OSGi specification. 
Once activated, a plug-in is only stopped when the OSGi container finishes its execution, or the plug-in is stopped by an OSGi command.


### Extensions and Plugins

A plugin owns an Extension, and an Extension implements an ExtensionPoint. The behaviour is defined below :-

* __Lifecycle__ : Each extension is created by a segment of code during the runtime execution, and destroyed/released whenever they are no longer needed. 
This has no influence with the plug-in lifecycle.
* __Manageability__ : In non managed environments, the plug-ins are managed by DataNucleus and maintained with a composition relation to the PMF/EMF instance. 
This allows a plug-in "instance" per PMF/EMF. If multiple PMF/EMFs are created multiple extensions for an ExtensionPoint are instantiated. 
In managed environments, more precisely in OSGi containers, the plug-ins are managed by the OSGi framework. Each plug-in will mostly be a singleton inside the OSGi container.
* __Registration__ : In non managed environments all plugins are registered using an instance of JDOClassLoaderResolver 
(so using the current ClassLoader of the PMF/EMF and the current thread). This means that the `/plugin.xml` and `/META-INF/MANIFEST.MF` files 
must be accessible to the classloader. In managed environment this is handled by the container.
* __ClassLoading__ : The classloading in non managed environments is usually made of one  single ClassLoader, while in managed 
environments each plug-in has it's own ClassLoader.
* __Configuration__ : Some Extensions needs to retrieve a configuration that was set in the PMF/EMF. 
This means that Plug-ins should not hold singleton / static configurations if they want to serve to multiple PMFs at the same time.
* __Constructors/Methods__ : In order of having consistent and avoid changes to ExtensionPoint interfaces, the Extension 
Constructors or Methods (either one) should have receive a NucleusContext instance as argument. 
If by the time the ExtensionPoint is designed clearly there is usage for a NucleusContext, then the ExtensionPoint does not need to take the NucleusContext as argument, but keep in mind that 
a 3rd Extension may need one due to different reasons.
* __Instantiation__ : Inside the DataNucleus Core, regardless if the runtime is OSGi managed or non managed, extension instances are created per PMF/EMF. 
DataNucleus Extensions should always be created through a PluginManager, regardless if the managed environment would allow you to instantiate using their own interfaces. 
This allows DataNucleus and its Plug-ins to run in non managed environments.




NOTE: Each ExtensionPoint has attributes. If you want to override an extension that is included in DataNucleus itself then you need to specify the priority attribute, 
setting it to an integer (the default plugin has priority=0, so set to higher than this to override it).

NOTE: If you write a DataNucleus plugin and you either want it to be included in the DataNucleus distribution, or want it to be listed here then please contact us.


include::_extensions_mapping.adoc[leveloffset=+1]
include::_extensions_cache.adoc[leveloffset=+1]
include::_extensions_identity.adoc[leveloffset=+1]
include::_extensions_types.adoc[leveloffset=+1]
include::_extensions_other.adoc[leveloffset=+1]
include::_extensions_rdbms.adoc[leveloffset=+1]
